[package]
name = "nginx-car-range"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_ipld_dagcbor = "0.2.2"
cid = { version = "0.10.1", features = ["serde-codec"] }
serde = "1.0.152"
anyhow = "1.0.69"
integer-encoding = "3.0.4"
