on:
  workflow_run:
    workflows: [Releaser]
    types: [completed]
  workflow_dispatch:
  
jobs:
  releases-matrix:
    name: Release Binary
    if: ${{ github.event.workflow_dispatch || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      APP_VERSION: ""
    strategy:
      matrix:
        include:
          - asset_name: nginx-car-range-linux-amd64.so
            arch: amd64
          - asset_name: nginx-car-range-linux-arm64.so
            arch: arm64
    steps:
    - uses: actions/checkout@v3

    - name: Determine version
      run: echo "APP_VERSION=$(jq -r .version version.json)" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/${{ matrix.arch }}
        push: false
        tags: nginx-car-range:${{ env.APP_VERSION }}
        build-args: |
          MODE=release
          ARCH=${{ matrix.arch }}
        target: release
        outputs: type=local,dest=out

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: out/libnginx_car_range.so
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ env.APP_VERSION }}
